# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c44736f5933488e1f8b57f2af957a5c279a240a3621101770b0add97de4150e26e8a94ca51cf478c8b1485fb576fe49d915841e84aff68c036643710db0f057a

test:
  secret_key_base: 963ed8a108d3205aa19ec7101a229efcbf968422fdd8c2c0117984a4df0c9ce344916fdf33082993e126dccb1a23e1bbaac427f7e388cc43bfa5bb39b9ce7b65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: c44736f5933488e1f8b57f2af957a5c279a240a3621101770b0add97de4150e26e8a94ca51cf478c8b1485fb576fe49d915841e84aff68c036643710db0f057a
